FROM node:8.10.0

# Use bundler cache
ENV NPM_CONFIG_PREFIX=/node_modules

# Set up working directory
ENV APP_HOME=/i2i-loopback-base

RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD . $APP_HOME

#RUN npm install

#RUN npm install pm2 -g
